title: Victor Hugo Brandao
description: Portfolio showcasing my education, work experience, and projects.
logo: /assets/img/profile-modified.png
#text:
#show_downloads: true
theme: jekyll-theme-minimal
